server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: jbdc:postgresql://localhost:5432/ekoms
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  expiration: 86400

logging:
  level:
    org.springframework.security: DEBUG
    com.ekoms.userservice: DEBUG
